"use strict";
app.config(["$stateProvider","$urlRouterProvider",function($stateProvider,$urlRouterProvider){
	$stateProvider.state("main",{
		url:"/main",
		templateUrl:"../view/template/main.html",
		controller:"mainCtrl",
	})
	.state("my",{
		url:"/my",
		templateUrl:"../view/template/my.html",
		controller:"myCtrl",
	})
	.state("search",{
		url:"/search",
		templateUrl:"../view/template/search.html",
		controller:"searchCtrl",
	})
	.state("position",{
		url:"/position/:id",
		templateUrl:"../view/template/position.html",
		controller:"positionCtrl"
	})
	.state("company",{
		url:"/company/:id",
		templateUrl:"../view/template/company.html",
		controller:"companyCtrl"
	})
	.state("login",{
		url:"/login",
		templateUrl:"../view/template/login.html",
		controller:"loginCtrl"
	})
	.state("register",{
		url:"/register",
		templateUrl:"../view/template/register.html",
		controller:"registerCtrl"
	})
	.state("favorite",{
		url:"/favorite",
		templateUrl:"../view/template/favorite.html",
		controller:"favoriteCtrl"
	})
	.state("post",{
		url:"/post",
		templateUrl:"../view/template/post.html",
		controller:"postCtrl"
	});

	$urlRouterProvider.otherwise("main");
}])